In [2]:
!pip install datasets evaluate rouge_score

Collecting datasets
  Downloading datasets-2.17.0-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.6/536.6 kB 4.0 MB/s eta 0:00:00
Collecting evaluate
  Downloading evaluate-0.4.1-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.5 MB/s eta 0:00:00
Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.13.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.23.5)
Collecting pyarrow>=12.0.0 (from datasets)
  Downloading pyarrow-15.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (38.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.3/38.3 MB 31.4 MB/s eta 0:00:00
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets) (0.6)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 746.3 kB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (1.5.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.66.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.4.1)
Collecting multiprocess (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 13.2 MB/s eta 0:00:00
Requirement already satisfied: fsspec[http]<=2023.10.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2023.6.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.9.3)
Requirement already satisfied: huggingface-hub>=0.19.4 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.20.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.1)
Collecting responses<0.19 (from evaluate)
  Downloading responses-0.18.0-py3-none-any.whl (38 kB)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from rouge_score) (3.8.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from rouge_score) (1.16.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.19.4->datasets) (4.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (2024.2.2)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score) (2023.12.25)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2023.4)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24933 sha256=63e9da25daca19be66cbd1522c817fa5fe4d7d234df7ba6ec67ae2b89ce3d367
  Stored in directory: /root/.cache/pip/wheels/5f/dd/89/461065a73be61a532ff8599a28e9beef17985c9e9c31e541b4
Successfully built rouge_score
Installing collected packages: pyarrow, dill, rouge_score, responses, multiprocess, datasets, evaluate
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 10.0.1
    Uninstalling pyarrow-10.0.1:
      Successfully uninstalled pyarrow-10.0.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ibis-framework 7.1.0 requires pyarrow<15,>=2, but you have pyarrow 15.0.0 which is incompatible.
Successfully installed datasets-2.17.0 dill-0.3.8 evaluate-0.4.1 multiprocess-0.70.16 pyarrow-15.0.0 responses-0.18.0 rouge_score-0.1.2

In [3]:
!pip install evaluate
!pip install rouge-score

Requirement already satisfied: evaluate in /usr/local/lib/python3.10/dist-packages (0.4.1)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.23.5)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.5.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from evaluate) (4.66.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec[http]>=2021.05.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2023.6.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.20.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from evaluate) (23.2)
Requirement already satisfied: responses<0.19 in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.18.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.13.1)
Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (15.0.0)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (0.6)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.9.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2024.2.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2023.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->evaluate) (1.16.0)
Requirement already satisfied: rouge-score in /usr/local/lib/python3.10/dist-packages (0.1.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from rouge-score) (3.8.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from rouge-score) (1.23.5)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from rouge-score) (1.16.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (2023.12.25)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (4.66.1)

In [4]:
import evaluate
rouge = evaluate.load('rouge')

Downloading builder script:   0%|          | 0.00/6.27k [00:00<?, ?B/s]

In [5]:
from datasets import load_dataset
ds = load_dataset("allenai/scitldr", name="AIC")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading data:   0%|          | 0.00/7.23M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/2.25M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1992 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/618 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/619 [00:00<?, ? examples/s]

In [6]:
ds

DatasetDict({
    train: Dataset({
        features: ['source', 'source_labels', 'rouge_scores', 'paper_id', 'ic', 'target'],
        num_rows: 1992
    })
    test: Dataset({
        features: ['source', 'source_labels', 'rouge_scores', 'paper_id', 'ic', 'target'],
        num_rows: 618
    })
    validation: Dataset({
        features: ['source', 'source_labels', 'rouge_scores', 'paper_id', 'ic', 'target'],
        num_rows: 619
    })
})

In [7]:
print()
print(f"Train dataset size: {len(ds['train'])}")
print()
print(f"Test dataset size: {len(ds['test'])}")
print()
print(f"Validation dataset size: {len(ds['validation'])}")
print()
print(f"Source example: {ds['train']['source'][0]}")
print()
print(f"Target example: {ds['train']['target'][0]}")
print()

Train dataset size: 1992

Test dataset size: 618

Validation dataset size: 619

Source example: ['Due to the success of deep learning to solving a variety of challenging machine learning tasks, there is a rising interest in understanding loss functions for training neural networks from a theoretical aspect.', 'Particularly, the properties of critical points and the landscape around them are of importance to determine the convergence performance of optimization algorithms.', 'In this paper, we provide a necessary and sufficient characterization of the analytical forms for the critical points (as well as global minimizers) of the square loss functions for linear neural networks.', 'We show that the analytical forms of the critical points characterize the values of the corresponding loss functions as well as the necessary and sufficient conditions to achieve global minimum.', 'Furthermore, we exploit the analytical forms of the critical points to characterize the landscape properties for the loss functions of linear neural networks and shallow ReLU networks.', 'One particular conclusion is that: While the loss function of linear networks has no spurious local minimum, the loss function of one-hidden-layer nonlinear networks with ReLU activation function does have local minimum that is not global minimum.', 'In the past decade, deep neural networks BID8 have become a popular tool that has successfully solved many challenging tasks in a variety of areas such as machine learning, artificial intelligence, computer vision, and natural language processing, etc.', 'As the understandings of deep neural networks from different aspects are mostly based on empirical studies, there is a rising need and interest to develop understandings of neural networks from theoretical aspects such as generalization error, representation power, and landscape (also referred to as geometry) properties, etc.', 'In particular, the landscape properties of loss functions (that are typically nonconex for neural networks) play a central role to determine the iteration path and convergence performance of optimization algorithms.One major landscape property is the nature of critical points, which can possibly be global minima, local minima, saddle points.', 'There have been intensive efforts in the past into understanding such an issue for various neural networks.', 'For example, it has been shown that every local minimum of the loss function is also a global minimum for shallow linear networks under the autoencoder setting and invertibility assumptions BID1 and for deep linear networks BID11 ; BID14 ; Yun et al. (2017) respectively under different assumptions.', 'The conditions on the equivalence between local minimum or critical point and global minimum has also been established for various nonlinear neural networks Yu & Chen (1995) ; BID9 ; BID15 ; BID17 ; BID6 under respective assumptions.However, most previous studies did not provide characterization of analytical forms for critical points of loss functions for neural networks with only very few exceptions.', 'In BID1 , the authors provided an analytical form for the critical points of the square loss function of shallow linear networks under certain conditions.', 'Such an analytical form further helps to establish the landscape properties around the critical points.', 'Further in BID13 , the authors characterized certain sufficient form of critical points for the square loss function of matrix factorization problems and deep linear networks.The focus of this paper is on characterizing the sufficient and necessary forms of critical points for broader scenarios, i.e., shallow and deep linear networks with no assumptions on data matrices and network dimensions, and shallow ReLU networks over certain parameter space.', 'In particular, such analytical forms of critical points capture the corresponding loss function values and the necessary and sufficient conditions to achieve global minimum.', 'This further enables us to establish new landscape properties around these critical points for the loss function of these networks under general settings, and provides alternative (yet simpler and more intuitive) proofs for existing understanding of the landscape properties.OUR CONTRIBUTION', '1) For the square loss function of linear networks with one hidden layer, we provide a full (necessary and sufficient) characterization of the analytical forms for its critical points and global minimizers.', 'These results generalize the characterization in BID1 to arbitrary network parameter dimensions and any data matrices.', 'Such a generalization further enables us to establish the landscape property, i.e., every local minimum is also a global minimum and all other critical points are saddle points, under no assumptions on parameter dimensions and data matrices.', 'From a technical standpoint, we exploit the analytical forms of critical points to provide a new proof for characterizing the landscape around the critical points under full relaxation of assumptions, where the corresponding approaches in BID1 are not applicable.', 'As a special case of linear networks, the matrix factorization problem satisfies all these landscape properties.2) For the square loss function of deep linear networks, we establish a full (necessary and sufficient) characterization of the analytical forms for its critical points and global minimizers.', 'Such characterizations are new and have not been established in the existing art.', 'Furthermore, such analytical form divides the set of non-global-minimum critical points into different categories.', 'We identify the directions along which the loss function value decreases for two categories of the critical points, for which our result directly implies the equivalence between the local minimum and the global minimum.', 'For these cases, our proof generalizes the result in BID11 under no assumptions on the network parameter dimensions and data matrices.3) For the square loss function of one-hidden-layer nonlinear neural networks with ReLU activation function, we provide a full characterization of both the existence and the analytical forms of the critical points in certain types of regions in the parameter space.', 'Particularly, in the case where there is one hidden unit, our results fully characterize the existence and the analytical forms of the critical points in the entire parameter space.', 'Such characterization were not provided in previous work on nonlinear neural networks.', 'Moreover, we apply our results to a concrete example to demonstrate that both local minimum that is not a global minimum and local maximum do exist in such a case.', 'In this paper, we provide full characterization of the analytical forms of the critical points for the square loss function of three types of neural networks, namely, shallow linear networks, deep linear networks, and shallow ReLU nonlinear networks.', 'We show that such analytical forms of the critical points have direct implications on the values of the corresponding loss functions, achievement of global minimum, and various landscape properties around these critical points.', 'As a consequence, the loss function for linear networks has no spurious local minimum, while such point does exist for nonlinear networks with ReLU activation.', 'In the future, it is interesting to further explore nonlinear neural networks.', 'In particular, we wish to characterize the analytical form of critical points for deep nonlinear networks and over the full parameter space.', 'Such results will further facilitate the understanding of the landscape properties around these critical points.']

Target example: ['We provide necessary and sufficient analytical forms for the critical points of the square loss functions for various neural networks, and exploit the analytical forms to characterize the landscape properties for the loss functions of these neural networks.']

In [8]:
import pandas as pd
dftrain = pd.DataFrame(ds["train"])
dftrain.head()

,source,source_labels,rouge_scores,paper_id,ic,target
0,[Due to the success of deep learning to solvin...,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.30188679695129395, 0.3720930218696594, 0.60...",SysEexbRb,True,[We provide necessary and sufficient analytica...
1,[The backpropagation (BP) algorithm is often t...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.0, 0.0, 0.1304347813129425, 0.1428571343421...",SygvZ209F7,True,"[Biologically plausible learning algorithms, p..."
2,"[We introduce the 2-simplicial Transformer, an...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.3333333432674408, 0.8888888955116272, 0.114...",rkecJ6VFvr,True,[We introduce the 2-simplicial Transformer and...
3,"[We present Tensor-Train RNN (TT-RNN), a novel...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.06666666269302368, 0.06451612710952759, 0.0...",HJJ0w--0W,True,[Accurate forecasting over very long time hori...
4,[Recent efforts on combining deep models with ...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.277777761220932, 0.5714285373687744, 0.0952...",HyH9lbZAW,True,[We propose a variational message-passing algo...

In [9]:
dftest = pd.DataFrame(ds["test"])
dftest.head()

,source,source_labels,rouge_scores,paper_id,ic,target
0,[Incremental class learning involves sequentia...,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.2857142686843872, 0.1818181723356247, 0.227...",SJ1Xmf-Rb,True,"[FearNet is a memory efficient neural-network,..."
1,[Multi-view learning can provide self-supervis...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...","[0.20000000298023224, 0.0, 0.15789473056793213...",S1xzyhR9Y7,True,[Multi-view learning improves unsupervised sen...
2,[We show how discrete objects can be learnt in...,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.978723406791687, 0.3333333432674408, 0.4150...",HJDUjKeA-,True,[We show how discrete objects can be learnt in...
3,[Most recent gains in visual recognition have ...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.11764705181121826, 0.1463414579629898, 0.19...",BJgLg3R9KQ,True,[A large-scale dataset for training attention ...
4,"[In recent years, deep neural networks have de...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.0, 0.05882352590560913, 0.2702702581882477,...",BklpOo09tQ,True,[We proposed a time-efficient defense method a...

In [10]:
dfval = pd.DataFrame(ds["validation"])
dfval.head()

,source,source_labels,rouge_scores,paper_id,ic,target
0,[Mixed precision training (MPT) is becoming a ...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.23999999463558197, 0.260869562625885, 0.199...",rJlnfaNYvB,True,[We devise adaptive loss scaling to improve mi...
1,"[Many real-world problems, e.g. object detecti...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.05405404791235924, 0.2926829159259796, 0.97...",rJVoEiCqKQ,True,[We present a novel approach for learning to p...
2,[Foveation is an important part of human visio...,"[0, 0, 1, 0, 0]","[0.11764705181121826, 0.11764705181121826, 0.3...",rkldVXKU8H,False,[We compare object recognition performance on ...
3,[We explore the concept of co-design in the co...,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.1249999925494194, 0.4888888895511627, 0.204...",BJfIVjAcKm,True,[We develop methods to train deep neural model...
4,[Batch Normalization (BatchNorm) has shown to ...,"[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.19999998807907104, 0.23999999463558197, 0.4...",BJlEEaEFDS,True,[Investigation of how BatchNorm causes adversa...

In [11]:
dftrain = dftrain.rename(columns={"target":"target_text", "source":"source_text"})
dftrain = dftrain[['source_text', 'target_text']]
dftrain.head()

,source_text,target_text
0,[Due to the success of deep learning to solvin...,[We provide necessary and sufficient analytica...
1,[The backpropagation (BP) algorithm is often t...,"[Biologically plausible learning algorithms, p..."
2,"[We introduce the 2-simplicial Transformer, an...",[We introduce the 2-simplicial Transformer and...
3,"[We present Tensor-Train RNN (TT-RNN), a novel...",[Accurate forecasting over very long time hori...
4,[Recent efforts on combining deep models with ...,[We propose a variational message-passing algo...

In [12]:
dftest = dftest.rename(columns={"target":"target_text", "source":"source_text"})
dftest = dftest[['source_text', 'target_text']]
dftest.head()

,source_text,target_text
0,[Incremental class learning involves sequentia...,"[FearNet is a memory efficient neural-network,..."
1,[Multi-view learning can provide self-supervis...,[Multi-view learning improves unsupervised sen...
2,[We show how discrete objects can be learnt in...,[We show how discrete objects can be learnt in...
3,[Most recent gains in visual recognition have ...,[A large-scale dataset for training attention ...
4,"[In recent years, deep neural networks have de...",[We proposed a time-efficient defense method a...

In [13]:
dfval = dfval.rename(columns={"target":"target_text", "source":"source_text"})
dfval = dfval[['source_text', 'target_text']]
dfval.head()

,source_text,target_text
0,[Mixed precision training (MPT) is becoming a ...,[We devise adaptive loss scaling to improve mi...
1,"[Many real-world problems, e.g. object detecti...",[We present a novel approach for learning to p...
2,[Foveation is an important part of human visio...,[We compare object recognition performance on ...
3,[We explore the concept of co-design in the co...,[We develop methods to train deep neural model...
4,[Batch Normalization (BatchNorm) has shown to ...,[Investigation of how BatchNorm causes adversa...

In [14]:
dftrain['source_text'] = dftrain['source_text'].apply(lambda x: ' '.join(x))
dftrain['target_text'] = dftrain['target_text'].apply(lambda x: ' '.join(x))
dftrain

,source_text,target_text
0,Due to the success of deep learning to solving...,We provide necessary and sufficient analytical...
1,The backpropagation (BP) algorithm is often th...,"Biologically plausible learning algorithms, pa..."
2,"We introduce the 2-simplicial Transformer, an ...",We introduce the 2-simplicial Transformer and ...
3,"We present Tensor-Train RNN (TT-RNN), a novel ...",Accurate forecasting over very long time horiz...
4,Recent efforts on combining deep models with p...,We propose a variational message-passing algor...
...,...,...
1987,"Semi-supervised learning, i.e. jointly learnin...",Pseudo-labeling has shown to be a weak alterna...
1988,Model-free reinforcement learning (RL) has bee...,We show that a special goal-condition value fu...
1989,We introduce a neural architecture to perform ...,A novel neural architecture for efficient amor...
1990,Machine learned large-scale retrieval systems ...,We propose a novel two-tower shared-bottom mod...
1991,The ability to autonomously explore and naviga...,We address the task of autonomous exploration ...

In [15]:
dftest['source_text'] = dftest['source_text'].apply(lambda x: ' '.join(x))
dftest['target_text'] = dftest['target_text'].apply(lambda x: ' '.join(x))
dftest

,source_text,target_text
0,Incremental class learning involves sequential...,"FearNet is a memory efficient neural-network, ..."
1,Multi-view learning can provide self-supervisi...,Multi-view learning improves unsupervised sent...
2,We show how discrete objects can be learnt in ...,We show how discrete objects can be learnt in ...
3,Most recent gains in visual recognition have o...,A large-scale dataset for training attention m...
4,"In recent years, deep neural networks have dem...",We proposed a time-efficient defense method ag...
...,...,...
613,Generative adversarial training can be general...,This paper studies the discrimination and gene...
614,Normalization layers are a staple in state-of-...,All you need to train deep residual networks i...
615,Designing a metric manually for unsupervised s...,This paper aims to learn a better metric for u...
616,One of the most successful techniques in gener...,Decompose the task of learning a generative mo...
617,Visual grounding of language is an active rese...,We propose a joint model to incorporate visual...

In [16]:
dfval['source_text'] = dfval['source_text'].apply(lambda x: ' '.join(x))
dfval['target_text'] = dfval['target_text'].apply(lambda x: ' '.join(x))
dfval

,source_text,target_text
0,Mixed precision training (MPT) is becoming a p...,We devise adaptive loss scaling to improve mix...
1,"Many real-world problems, e.g. object detectio...",We present a novel approach for learning to pr...
2,Foveation is an important part of human vision...,We compare object recognition performance on i...
3,We explore the concept of co-design in the con...,We develop methods to train deep neural models...
4,Batch Normalization (BatchNorm) has shown to b...,Investigation of how BatchNorm causes adversar...
...,...,...
614,Policy gradients methods often achieve better ...,Linking Wasserstein-trust region entropic poli...
615,The softmax function is widely used to train d...,The discriminative capability of softmax for l...
616,A fundamental question in reinforcement learni...,We adapt Q-learning with UCB-exploration bonus...
617,Backpropagation is driving today's artificial ...,Perturbations can be used to train feedback we...
618,This paper proposes and demonstrates a surpris...,"We identify some universal patterns (i.e., hol..."

In [17]:
dftest['target_text']

0      FearNet is a memory efficient neural-network, ...
1      Multi-view learning improves unsupervised sent...
2      We show how discrete objects can be learnt in ...
3      A large-scale dataset for training attention m...
4      We proposed a time-efficient defense method ag...
                             ...
613    This paper studies the discrimination and gene...
614    All you need to train deep residual networks i...
615    This paper aims to learn a better metric for u...
616    Decompose the task of learning a generative mo...
617    We propose a joint model to incorporate visual...
Name: target_text, Length: 618, dtype: object

In [18]:
reference = dftest['target_text'].tolist()
reference[0:3]

['FearNet is a memory efficient neural-network, inspired by memory formation in the mammalian brain, that is capable of incremental class learning without catastrophic forgetting. This paper presents a novel solution to an incremental classification problem based on a dual memory system. ',
 'Multi-view learning improves unsupervised sentence representation learning Approach uses different, complementary encoders of the input sentence and consensus maximization. The paper presents a multi-view framework for improving sentence representation in NLP tasks using generative and discriminative objective architectures. This paper shows that multi-view frameworks are more effective than using individual encoders for learning sentence representations.',
 'We show how discrete objects can be learnt in an unsupervised fashion from pixels, and how to perform reinforcement learning using this object representation. A method for learning object representations from pixels for doing reinforcement learning.  The paper proposes a neural architecture to map video streams to a discrete collection of objects, without human annotations, using an unsupervised pixel reconstruction loss. ']

In [19]:
def predict(text):
  import spacy
  nlp = spacy.load('en_core_web_sm')
  doc = nlp(text)
  from spacy.lang.en.stop_words import STOP_WORDS
  stopwords = list(STOP_WORDS)
  from string import punctuation
  punctuation = punctuation + '\n'

  wordfreq = {}
  for word in doc:
    if word.text.lower() not in stopwords:
      if word.text.lower() not in punctuation:
        if word.text not in wordfreq.keys():
          wordfreq[word.text] = 1
        else:
          wordfreq[word.text] += 1
  for word in wordfreq.keys():
    wordfreq[word] = wordfreq[word]/max(wordfreq.values())

  senttokens = [i for i in doc.sents]

  sentweight = {}
  for sent in senttokens:
    for word in sent:
      if word.text.lower() in wordfreq.keys():
        if sent not in sentweight.keys():
          sentweight[sent] = wordfreq[word.text.lower()]
        else:
          sentweight[sent] += wordfreq[word.text.lower()]

  from heapq import nlargest
  sizee=int(len(senttokens)*0.1)
  summ=nlargest(sizee, sentweight, key=sentweight.get)

  spacy_res = [word.text for word in summ]

  spacy_result = ' '.join(spacy_res)
  return spacy_result

In [34]:
prediction=[]
c=0
for i in dftest['source_text']:
  sp_pred=predict(i)
  c=c+1
  print(c)
  prediction.append(sp_pred)
  if c==100:
    break;

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [36]:
results_spacy = rouge.compute(predictions=prediction, references=reference[0:100])
print(results_spacy) #ROUGE-1 score of 0.25 or higher is considered acceptable for scientific paper summarization

{'rouge1': 0.2570280873653559, 'rouge2': 0.054792732868739494, 'rougeL': 0.14368666632672134, 'rougeLsum': 0.1456649526813732}